name: release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build release binary
        run: make

      - name: Upload binary
        uses: actions/upload-artifact@v4
        env:
          GITHUB_TOKEN: ${{ secrets.WARWICK_TOKEN_LEAGUE_OF_LEGEND }}
        with:
          name: dummydb-binary
          path: build/main
          upload_url: ${{ github.event.release.upload_url }}

      - name: Upload LICENSE
        uses: actions/upload-artifact@v4
        env:
          GITHUB_TOKEN: ${{ secrets.WARWICK_TOKEN_LEAGUE_OF_LEGEND }}
        with:
          name: LICENSE
          path: LICENSE
          upload_url: ${{ github.event.release.upload_url }}