name: release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build release binary
        run: make

      - name: Upload binary
        uses: actions/upload-release-artifact@v1
        env:
          GITHUB_TOKEN: ${{ secrets.WARWICK_TOKEN_LEAGUE_OF_LEGEND }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_name: dummydb-binary
          asset_path: ./build/main
          asset_content_type: application/octet-stream

      - name: Upload LICENSE
        uses: actions/upload-release-artifact@v1
        env:
          GITHUB_TOKEN: ${{ secrets.WARWICK_TOKEN_LEAGUE_OF_LEGEND }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_name: LICENSE
          asset_path: LICENSE
          asset_content_type: text/plain